var prodList = [
  {
    id: 0,
    prodName: "Camiseta Black Pocket",
    prodPrice: "100",
    prodImg1: "/img/camisetaA1.webp",
    prodImg2: "/img/camisetaA2.webp",
    prodImg3: "/img/camisetaA3.webp",
    prodImg4: "/img/camisetaA4.webp",
    prodQtd: 1,
  },
  {
    id: 1,
    prodName: "Camiseta RJ Black",
    prodPrice: "110",
    prodImg1: "/img/camisetaG1.webp",
    prodImg2: "/img/camisetaG2.webp",
    prodImg3: "/img/camisetaG3.webp",
    prodImg4: "/img/camisetaG4.webp",
    prodQtd: 1,
  },
  {
    id: 2,
    prodName: "Camiseta Oliver Bra",
    prodPrice: "120",
    prodImg1: "/img/camisetaB1.webp",
    prodImg2: "/img/camisetaB2.webp",
    prodImg3: "/img/camisetaB3.webp",
    prodImg4: "/img/camisetaB4.webp",
    prodQtd: 1,
  },
  {
    id: 3,
    prodName: "Camiseta Simple blue",
    prodPrice: "130",
    prodImg1: "/img/camisetaC1.webp",
    prodImg2: "/img/camisetaC2.webp",
    prodImg3: "/img/camisetaC3.webp",
    prodImg4: "/img/camisetaC4.webp",
    prodQtd: 1,
  },
  {
    id: 4,
    prodName: "Camiseta Naivy Listed",
    prodPrice: "140",
    prodImg1: "/img/camisetaD1.webp",
    prodImg2: "/img/camisetaD2.webp",
    prodImg3: "/img/camisetaD3.webp",
    prodImg4: "/img/camisetaD4.webp",
    prodQtd: 1,
  },
  {
    id: 5,
    prodName: "Camiseta Black Pocket2",
    prodPrice: "150",
    prodImg1: "/img/camisetaA1.webp",
    prodImg2: "/img/camisetaA2.webp",
    prodImg3: "/img/camisetaA3.webp",
    prodImg4: "/img/camisetaA4.webp",
    prodQtd: 1,
  },
  {
    id: 6,
    prodName: "Camiseta Black Degrader2",
    prodPrice: "160",
    prodImg1: "/img/camisetaH1.webp",
    prodImg2: "/img/camisetaH2.webp",
    prodImg3: "/img/camisetaH3.webp",
    prodImg4: "/img/camisetaH4.webp",
    prodQtd: 1,
  },
  {
    id: 7,
    prodName: "Camiseta Oliver Bra2",
    prodPrice: "170",
    prodImg1: "/img/camisetaB1.webp",
    prodImg2: "/img/camisetaB2.webp",
    prodImg3: "/img/camisetaB3.webp",
    prodImg4: "/img/camisetaB4.webp",
    prodQtd: 1,
  },
  {
    id: 8,
    prodName: "Camiseta Triangulo2",
    prodPrice: "180",
    prodImg1: "/img/camisetaE1.webp",
    prodImg2: "/img/camisetaE2.webp",
    prodImg3: "/img/camisetaE3.webp",
    prodImg4: "/img/camisetaE4.webp",
    prodQtd: 1,
  },
  {
    id: 9,
    prodName: "Camiseta Naivy Listed2",
    prodPrice: "190",
    prodImg1: "/img/camisetaD1.webp",
    prodImg2: "/img/camisetaD2.webp",
    prodImg3: "/img/camisetaD3.webp",
    prodImg4: "/img/camisetaD4.webp",
    prodQtd: 1,
  },
  {
    id: 10,
    prodName: "Camiseta Terra2",
    prodPrice: "200",
    prodImg1: "/img/camisetaF1.webp",
    prodImg2: "/img/camisetaF2.webp",
    prodImg3: "/img/camisetaF3.webp",
    prodImg4: "/img/camisetaF4.webp",
    prodQtd: 1,
  },
  {
    id: 11,
    prodName: "Camiseta RJ Black2",
    prodPrice: "210",
    prodImg1: "/img/camisetaG1.webp",
    prodImg2: "/img/camisetaG2.webp",
    prodImg3: "/img/camisetaG3.webp",
    prodImg4: "/img/camisetaG4.webp",
    prodQtd: 1,
  },
  {
    id: 12,
    prodName: "Camiseta Triangulo",
    prodPrice: "220",
    prodImg1: "/img/camisetaE1.webp",
    prodImg2: "/img/camisetaE2.webp",
    prodImg3: "/img/camisetaE3.webp",
    prodImg4: "/img/camisetaE4.webp",
    prodQtd: 1,
  },
  {
    id: 13,
    prodName: "Camiseta Black Degrader",
    prodPrice: "230",
    prodImg1: "/img/camisetaH1.webp",
    prodImg2: "/img/camisetaH2.webp",
    prodImg3: "/img/camisetaH3.webp",
    prodImg4: "/img/camisetaH4.webp",
    prodQtd: 1,
  },
  {
    id: 14,
    prodName: "Camiseta Terra",
    prodPrice: "240",
    prodImg1: "/img/camisetaF1.webp",
    prodImg2: "/img/camisetaF2.webp",
    prodImg3: "/img/camisetaF3.webp",
    prodImg4: "/img/camisetaF4.webp",
    prodQtd: 1,
  },
  {
    id: 15,
    prodName: "Camiseta Triangulo",
    prodPrice: "250",
    prodImg1: "/img/camisetaE1.webp",
    prodImg2: "/img/camisetaE2.webp",
    prodImg3: "/img/camisetaE3.webp",
    prodImg4: "/img/camisetaE4.webp",
    prodQtd: 1,
  },
];

export default prodList;
